# encoding: utf-8
#
# Cookbook Name:: os-hardening
# Attributes:: default
#
# Copyright 2012, Dominik Richter
# Copyright 2014, Deutsche Telekom AG
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# rhel, centos autoconf configuration
default['authconfig']['shadow']['enable'] = true
default['authconfig']['md5']['enable'] = true

default['config_disclaimer']                         = '#**Caution:** This file is generated by Chef. Do not edit Manually, changes will be overwritten in next converge' 
default['desktop']['enable']                          = false
default['network']['forwarding']                      = false
default['network']['ipv6']['enable']                   = false
default['network']['arp']['restricted']                = true
default['env']['extra_user_paths']                    = []
default['env']['umask']                               = '0027'
default['env']['root_path']                           = '/'
default['auth']['pw_max_age']                         = 90
default['auth']['pw_min_age']                         = 15 # discourage password cycling
default['auth']['pw_warn_age']						  = 7 # newly added
default['auth']['acnt_inactive_age']				  = 90 # newly added
default['auth']['pw_tiviality']						  = 'password requisite pam_cracklib.so try_first_pass retry=3 minlength=10 difok=2 lcredit=1 ucredit=1 dcredit=1 ocredit=2' # newly added
default['auth']['pw_min_len']						  = 8
default['auth']['retries']                            = 4
default['auth']['lockout_time']                       = 300 # 10min
default['auth']['timeout']                            = 60
default['auth']['allow_homeless']                     = false
default['auth']['pam']['passwdqc']['enable']            = true
default['auth']['pam']['passwdqc']['options']           = 'min=disabled,disabled,16,12,8'
default['auth']['root_ttys']                          = %w(console tty1 tty2 tty3 tty4 tty5 tty6)
default['auth']['uid_min']                             = 1000
default['auth']['gid_min']                             = 1000
# may contain: change_user
default['security']['users']['nologin']	= [
  'bin', 'daemon', 'adm', 'lp', 'uucp', 'operator', 
  'nobody', 'dbus', 'avahi', 'smmsp', 'mail', 'ntp', 
  'haldaemon', 'sshd', 'gdm', 'xfs', 'sabayon', 'sync',
  'shutdown', 'halt', 'news', 'games', 'gopher', 'ftp', 
  'nscd', 'distcache', 'vcsa', 'pcap', 'apache', 'rpc', 
  'nfsnobody', 'webalizer', 'dovecot', 'squid', 'mailnull', 
  'hsqldb', 'dbus', 'named', 'avahi-autoipd', 'gdm'
]
  
default['security']['users']['allow']                  = []
default['security']['kernel']['enable_module_loading'] = true
default['security']['kernel']['enable_sysrq']          = false
default['security']['kernel']['enable_core_dump']      = false
default['security']['suid_sgid']['enforce']            = true
# user-defined blacklist and whitelist
default['security']['suid_sgid']['blacklist']          = []
default['security']['suid_sgid']['whitelist']          = []
# if this is true, remove any suid/sgid bits from files that were not in the
# whitelist
default['security']['suid_sgid']['remove_from_unknown'] = false
default['security']['suid_sgid']['dry_run_on_unknown']  = false

# remove packages with known issues
default['security']['packages']['clean']               = true
default['security']['patch']                           = false
default['ssh']['allowed-users']                        = 'cmonitor cmanage cbackup cadmin root'
default['ssh']['pubkey']                        = 'pubkey'
default['aide']['scanfile']			       = '/var/lib/aide/aide.db.new.gz'
default['sudo']['rootuser']			       = 'cadmin'

## Newly added attributes as per Cognizant hardening standards
default['services']['enable'] = [ 'ntpd', 'network', 'sshd', 'syslog', 
  'auditd', 'httpd', 'acpid', 'cpuspeed', 'crond', 'atd', 'anacron',
  'irqbalance', 'iptables', 'nagios', 'xinetd', 'sendmail'
]

  
default['security']['suid_sgid']['system_blacklist']          = [
  # blacklist as provided by NSA
  '/usr/bin/rcp', '/usr/bin/rlogin', '/usr/bin/rsh',
  # sshd must not use host-based authentication (see ssh cookbook)
  '/usr/libexec/openssh/ssh-keysign',
  '/usr/lib/openssh/ssh-keysign',
  # misc others
  '/sbin/netreport',                                            # not normally required for user
  '/usr/sbin/usernetctl',                                       # modify interfaces via functional accounts
  # connecting to ...
  '/usr/sbin/userisdnctl',                                      # no isdn...
  '/usr/sbin/pppd',                                             # no ppp / dsl ...
  # lockfile
  '/usr/bin/lockfile',
  '/usr/bin/mail-lock',
  '/usr/bin/mail-unlock',
  '/usr/bin/mail-touchlock',
  '/usr/bin/dotlockfile',
  # need more investigation, blacklist for now
  '/usr/bin/arping',
  '/usr/sbin/uuidd',
  '/usr/bin/mtr',                                               # investigate current state...
  '/usr/lib/evolution/camel-lock-helper-1.2',                   # investigate current state...
  '/usr/lib/pt_chown',                                          # pseudo-tty, needed?
  '/usr/lib/eject/dmcrypt-get-device',
  '/usr/lib/mc/cons.saver',                                      # midnight commander screensaver
  '/sbin/pam_timestamp_check',
  '/sbin/unix_chkpwd', '/usr/bin/at', '/usr/bin/gpasswd', '/usr/bin/locate',
  '/usr/bin/newgrp',  '/usr/libexec/utempter/utempter', '/usr/sbin/lockdev',
  '/usr/sbin/sendmail.sendmail', '/usr/bin/expiry',
  # whitelist ipv6
  '/bin/ping6', '/usr/bin/traceroute6.iputils',
  '/usr/bin/wall', '/usr/bin/write',
  # whitelist locate
  '/usr/bin/mlocate'
]

# list of suid/sgid entries that can remain untouched
default['security']['suid_sgid']['system_whitelist']          = [
  # whitelist as provided by NSA
  '/bin/mount', '/bin/ping', '/bin/su', '/bin/umount', '/usr/bin/passwd', '/usr/bin/mount',
  # whitelist nfs
  '/sbin/mount.nfs', '/sbin/umount.nfs',
  # whitelist nfs4
  '/sbin/mount.nfs4', '/sbin/umount.nfs4',
  # whitelist cron
  '/usr/bin/crontab',
  '/usr/sbin/rhnsd', '/usr/sbin/rhn-profile-sync', '/usr/sbin/rhn_register', '/usr/sbin/rhn_check', '/usr/sbin/rhnreg_ks', '/usr/bin/passwd', '/usr/bin/curl', '/bin/ping', '/bin/su', '/usr/bin/sudo', '/usr/bin/sudoedit', '/usr/bin/su', '/usr/bin/sudo'
]
